const users = require("./users");
const recruiters = require("./recruiters");
const jobposts = require("./jobposts");
const workers = require("./workers");
const workExperience = require("./work_experiences");
const certifications = require("./certifications");
const workerSkills = require("./worker_skills");
const skills = require("./skills");
const education = require("./educations");
const language = require("./languages");
const resume = require("./resumes");
const jobtags = require("./job_tags");
const portfolio = require("./portfolios");
const industries = require("./industries");

module.exports = (server) => {
  users(server);
  recruiters(server);
  jobposts(server);
  workers(server);
  workExperience(server);
  workers(server);
  certifications(server);
  workerSkills(server);
  skills(server);
  education(server);
  language(server);
  resume(server);
  portfolio(server);
  jobtags(server);
  industries(server);
};
