const users = require("./users");
const recruiters = require("./recruiters");
const jobposts = require("./jobposts");
const workers = require("./workers");
const workExperience = require("./work_experiences");
const certifications = require("./certifications");
const workerSkills = require("./worker_skills");
const skills = require("./skills");
const education = require("./educations");
const language = require("./languages");
const resume = require("./resumes");
const jobtags = require("./job_tags");
const portfolio = require("./portfolios");
const industries = require("./industries");
const nationalities = require("./nationalities");
const genders = require("./genders");
const experienceLevels = require("./experience_levels");
const savedJobs = require("./saved_jobs");
const employmentTypes = require("./employment_types");
const categories = require('./categories');
const jobPostRequirements = require('./job_post_requirements');
const jobPostResponsibilities = require('./job_post_responsibilities');
const jobPostBenefits = require('./job_post_benefits');
const contact_us = require('./contact_us');
const locations = require('./locations');
const admin = require('./admin');
const payments = require('./payments');
const cvParsing = require('./cv_parsing');
const chat = require('./chat');
const candidatePipeline = require('./candidate_pipeline');
const communication = require('./communication');
const jobAlerts = require('./job_alerts');
const candidateMatching = require('./candidate_matching');
const news = require('./news');
const telegram = require('./telegram');


module.exports = (server) => {
  users(server);
  telegram(server);
  recruiters(server);
  jobposts(server);
  resume(server);
  workers(server);
  workExperience(server);
  certifications(server);
  workerSkills(server);
  skills(server);
  education(server);
  language(server);
  portfolio(server);
  jobtags(server);
  industries(server);
  nationalities(server);
  genders(server);
  experienceLevels(server);
  savedJobs(server);
  employmentTypes(server);
  categories(server);
  jobPostRequirements(server);
  jobPostResponsibilities(server);
  jobPostBenefits(server);
  contact_us(server);
  locations(server);
  admin(server);
  payments(server);
  cvParsing(server);
  chat(server);
  candidatePipeline(server);
  communication(server);
  jobAlerts(server);
  candidateMatching(server);
  news(server);
};

