-- TRUNCATE existing data before re-seeding
TRUNCATE TABLE cities RESTART IDENTITY CASCADE;
TRUNCATE TABLE provinces RESTART IDENTITY CASCADE;

-- =============================================
-- PROVINCES OF INDONESIA (38 Provinces)
-- =============================================
INSERT INTO provinces (id, name) VALUES
(1,  'Aceh'),
(2,  'Sumatera Utara'),
(3,  'Sumatera Barat'),
(4,  'Riau'),
(5,  'Jambi'),
(6,  'Sumatera Selatan'),
(7,  'Bengkulu'),
(8,  'Lampung'),
(9,  'Kepulauan Bangka Belitung'),
(10, 'Kepulauan Riau'),
(11, 'DKI Jakarta'),
(12, 'Jawa Barat'),
(13, 'Jawa Tengah'),
(14, 'DI Yogyakarta'),
(15, 'Jawa Timur'),
(16, 'Banten'),
(17, 'Bali'),
(18, 'Nusa Tenggara Barat'),
(19, 'Nusa Tenggara Timur'),
(20, 'Kalimantan Barat'),
(21, 'Kalimantan Tengah'),
(22, 'Kalimantan Selatan'),
(23, 'Kalimantan Timur'),
(24, 'Kalimantan Utara'),
(25, 'Sulawesi Utara'),
(26, 'Sulawesi Tengah'),
(27, 'Sulawesi Selatan'),
(28, 'Sulawesi Tenggara'),
(29, 'Gorontalo'),
(30, 'Sulawesi Barat'),
(31, 'Maluku'),
(32, 'Maluku Utara'),
(33, 'Papua Barat'),
(34, 'Papua'),
(35, 'Papua Selatan'),
(36, 'Papua Tengah'),
(37, 'Papua Pegunungan'),
(38, 'Papua Barat Daya');

-- =============================================
-- CITIES OF INDONESIA
-- =============================================
INSERT INTO cities (province_id, name) VALUES

-- Aceh (1)
(1, 'Banda Aceh'),
(1, 'Sabang'),
(1, 'Langsa'),
(1, 'Lhokseumawe'),
(1, 'Subulussalam'),
(1, 'Meulaboh'),
(1, 'Sigli'),
(1, 'Bireuen'),
(1, 'Takengon'),
(1, 'Kutacane'),

-- Sumatera Utara (2)
(2, 'Medan'),
(2, 'Binjai'),
(2, 'Tebing Tinggi'),
(2, 'Pematangsiantar'),
(2, 'Tanjungbalai'),
(2, 'Sibolga'),
(2, 'Padangsidimpuan'),
(2, 'Gunungsitoli'),
(2, 'Rantauprapat'),
(2, 'Balige'),
(2, 'Kabanjahe'),
(2, 'Lubuk Pakam'),

-- Sumatera Barat (3)
(3, 'Padang'),
(3, 'Bukittinggi'),
(3, 'Payakumbuh'),
(3, 'Padang Panjang'),
(3, 'Solok'),
(3, 'Sawahlunto'),
(3, 'Pariaman'),
(3, 'Painan'),
(3, 'Lubuk Basung'),
(3, 'Muaro Sijunjung'),

-- Riau (4)
(4, 'Pekanbaru'),
(4, 'Dumai'),
(4, 'Bengkalis'),
(4, 'Siak Sri Indrapura'),
(4, 'Bangkinang'),
(4, 'Rengat'),
(4, 'Tembilahan'),
(4, 'Pasir Pengarayan'),
(4, 'Bagan Batu'),
(4, 'Selat Panjang'),

-- Jambi (5)
(5, 'Jambi'),
(5, 'Sungai Penuh'),
(5, 'Muara Bungo'),
(5, 'Muara Bulian'),
(5, 'Sarolangun'),
(5, 'Bangko'),
(5, 'Kuala Tungkal'),
(5, 'Muara Sabak'),
(5, 'Sengeti'),

-- Sumatera Selatan (6)
(6, 'Palembang'),
(6, 'Prabumulih'),
(6, 'Pagaralam'),
(6, 'Lubuklinggau'),
(6, 'Baturaja'),
(6, 'Kayuagung'),
(6, 'Muara Enim'),
(6, 'Lahat'),
(6, 'Sekayu'),
(6, 'Indralaya'),

-- Bengkulu (7)
(7, 'Bengkulu'),
(7, 'Argamakmur'),
(7, 'Manna'),
(7, 'Curup'),
(7, 'Mukomuko'),
(7, 'Kaur'),
(7, 'Kepahiang'),

-- Lampung (8)
(8, 'Bandar Lampung'),
(8, 'Metro'),
(8, 'Kalianda'),
(8, 'Kotabumi'),
(8, 'Blambangan Umpu'),
(8, 'Gedong Tataan'),
(8, 'Pringsewu'),
(8, 'Liwa'),
(8, 'Menggala'),
(8, 'Sukadana'),

-- Kepulauan Bangka Belitung (9)
(9, 'Pangkal Pinang'),
(9, 'Sungailiat'),
(9, 'Tanjung Pandan'),
(9, 'Toboali'),
(9, 'Manggar'),
(9, 'Koba'),
(9, 'Muntok'),

-- Kepulauan Riau (10)
(10, 'Tanjungpinang'),
(10, 'Batam'),
(10, 'Tanjung Balai Karimun'),
(10, 'Daik'),
(10, 'Ranai'),
(10, 'Palmatak'),

-- DKI Jakarta (11)
(11, 'Jakarta Pusat'),
(11, 'Jakarta Utara'),
(11, 'Jakarta Barat'),
(11, 'Jakarta Selatan'),
(11, 'Jakarta Timur'),
(11, 'Kepulauan Seribu'),

-- Jawa Barat (12)
(12, 'Bandung'),
(12, 'Bekasi'),
(12, 'Bogor'),
(12, 'Cimahi'),
(12, 'Cirebon'),
(12, 'Depok'),
(12, 'Sukabumi'),
(12, 'Tasikmalaya'),
(12, 'Banjar'),
(12, 'Purwakarta'),
(12, 'Karawang'),
(12, 'Subang'),
(12, 'Indramayu'),
(12, 'Kuningan'),
(12, 'Majalengka'),
(12, 'Garut'),
(12, 'Cianjur'),
(12, 'Ciamis'),

-- Jawa Tengah (13)
(13, 'Semarang'),
(13, 'Surakarta'),
(13, 'Salatiga'),
(13, 'Magelang'),
(13, 'Pekalongan'),
(13, 'Tegal'),
(13, 'Kudus'),
(13, 'Jepara'),
(13, 'Demak'),
(13, 'Purwokerto'),
(13, 'Cilacap'),
(13, 'Kebumen'),
(13, 'Purworejo'),
(13, 'Wonosobo'),
(13, 'Boyolali'),
(13, 'Blora'),
(13, 'Rembang'),
(13, 'Pati'),
(13, 'Grobogan'),
(13, 'Ungaran'),
(13, 'Klaten'),
(13, 'Sragen'),
(13, 'Brebes'),
(13, 'Batang'),
(13, 'Pemalang'),
(13, 'Banjarnegara'),
(13, 'Temanggung'),
(13, 'Kendal'),
(13, 'Wonogiri'),
(13, 'Karanganyar'),

-- DI Yogyakarta (14)
(14, 'Yogyakarta'),
(14, 'Sleman'),
(14, 'Bantul'),
(14, 'Wates'),
(14, 'Wonosari'),

-- Jawa Timur (15)
(15, 'Surabaya'),
(15, 'Malang'),
(15, 'Batu'),
(15, 'Blitar'),
(15, 'Kediri'),
(15, 'Madiun'),
(15, 'Mojokerto'),
(15, 'Pasuruan'),
(15, 'Probolinggo'),
(15, 'Banyuwangi'),
(15, 'Jember'),
(15, 'Jombang'),
(15, 'Sidoarjo'),
(15, 'Gresik'),
(15, 'Bojonegoro'),
(15, 'Tuban'),
(15, 'Lamongan'),
(15, 'Pamekasan'),
(15, 'Sumenep'),
(15, 'Sampang'),
(15, 'Bangkalan'),
(15, 'Bondowoso'),
(15, 'Situbondo'),
(15, 'Lumajang'),
(15, 'Nganjuk'),
(15, 'Ponorogo'),
(15, 'Tulungagung'),
(15, 'Trenggalek'),
(15, 'Pacitan'),
(15, 'Ngawi'),
(15, 'Magetan'),

-- Banten (16)
(16, 'Serang'),
(16, 'Cilegon'),
(16, 'Tangerang'),
(16, 'Tangerang Selatan'),
(16, 'Pandeglang'),
(16, 'Lebak'),

-- Bali (17)
(17, 'Denpasar'),
(17, 'Gianyar'),
(17, 'Badung'),
(17, 'Tabanan'),
(17, 'Jembrana'),
(17, 'Buleleng'),
(17, 'Bangli'),
(17, 'Klungkung'),
(17, 'Karangasem'),

-- Nusa Tenggara Barat (18)
(18, 'Mataram'),
(18, 'Bima'),
(18, 'Sumbawa Besar'),
(18, 'Praya'),
(18, 'Selong'),
(18, 'Taliwang'),
(18, 'Woha'),
(18, 'Dompu'),

-- Nusa Tenggara Timur (19)
(19, 'Kupang'),
(19, 'Ende'),
(19, 'Maumere'),
(19, 'Labuan Bajo'),
(19, 'Ruteng'),
(19, 'Bajawa'),
(19, 'Waingapu'),
(19, 'Waikabubak'),
(19, 'Atambua'),
(19, 'Kefamenanu'),
(19, 'Soe'),
(19, 'Kalabahi'),

-- Kalimantan Barat (20)
(20, 'Pontianak'),
(20, 'Singkawang'),
(20, 'Sambas'),
(20, 'Mempawah'),
(20, 'Sanggau'),
(20, 'Ketapang'),
(20, 'Sintang'),
(20, 'Putussibau'),
(20, 'Ngabang'),
(20, 'Bengkayang'),

-- Kalimantan Tengah (21)
(21, 'Palangka Raya'),
(21, 'Sampit'),
(21, 'Pangkalan Bun'),
(21, 'Muara Teweh'),
(21, 'Buntok'),
(21, 'Nanga Bulik'),
(21, 'Kuala Kapuas'),
(21, 'Kasongan'),
(21, 'Sukamara'),
(21, 'Puruk Cahu'),

-- Kalimantan Selatan (22)
(22, 'Banjarmasin'),
(22, 'Banjarbaru'),
(22, 'Martapura'),
(22, 'Pelaihari'),
(22, 'Kotabaru'),
(22, 'Barabai'),
(22, 'Kandangan'),
(22, 'Tanjung'),
(22, 'Amuntai'),
(22, 'Rantau'),

-- Kalimantan Timur (23)
(23, 'Samarinda'),
(23, 'Balikpapan'),
(23, 'Bontang'),
(23, 'Tenggarong'),
(23, 'Sangatta'),
(23, 'Tanjung Redeb'),
(23, 'Penajam'),
(23, 'Sendawar'),
(23, 'Tanah Grogot'),
(23, 'Long Kali'),

-- Kalimantan Utara (24)
(24, 'Tanjung Selor'),
(24, 'Tarakan'),
(24, 'Nunukan'),
(24, 'Malinau'),
(24, 'Tideng Pale'),

-- Sulawesi Utara (25)
(25, 'Manado'),
(25, 'Bitung'),
(25, 'Tomohon'),
(25, 'Kotamobagu'),
(25, 'Tondano'),
(25, 'Amurang'),
(25, 'Tahuna'),
(25, 'Melonguane'),

-- Sulawesi Tengah (26)
(26, 'Palu'),
(26, 'Luwuk'),
(26, 'Poso'),
(26, 'Donggala'),
(26, 'Toli-Toli'),
(26, 'Buol'),
(26, 'Ampana'),
(26, 'Parigi'),
(26, 'Morowali'),
(26, 'Banggai'),

-- Sulawesi Selatan (27)
(27, 'Makassar'),
(27, 'Parepare'),
(27, 'Palopo'),
(27, 'Maros'),
(27, 'Sungguminasa'),
(27, 'Watampone'),
(27, 'Bulukumba'),
(27, 'Bantaeng'),
(27, 'Jeneponto'),
(27, 'Takalar'),
(27, 'Sinjai'),
(27, 'Barru'),
(27, 'Pinrang'),
(27, 'Enrekang'),
(27, 'Makale'),
(27, 'Masamba'),
(27, 'Sengkang'),
(27, 'Pangkajene'),

-- Sulawesi Tenggara (28)
(28, 'Kendari'),
(28, 'Bau-Bau'),
(28, 'Kolaka'),
(28, 'Unaaha'),
(28, 'Lasusua'),
(28, 'Raha'),
(28, 'Andoolo'),
(28, 'Wanggudu'),
(28, 'Bombana'),

-- Gorontalo (29)
(29, 'Gorontalo'),
(29, 'Marisa'),
(29, 'Kwandang'),
(29, 'Tilamuta'),
(29, 'Limboto'),
(29, 'Isimu'),

-- Sulawesi Barat (30)
(30, 'Mamuju'),
(30, 'Majene'),
(30, 'Polewali'),
(30, 'Pasangkayu'),
(30, 'Mamasa'),

-- Maluku (31)
(31, 'Ambon'),
(31, 'Tual'),
(31, 'Masohi'),
(31, 'Namlea'),
(31, 'Bula'),
(31, 'Saumlaki'),
(31, 'Dobo'),
(31, 'Tiakur'),

-- Maluku Utara (32)
(32, 'Sofifi'),
(32, 'Ternate'),
(32, 'Tidore'),
(32, 'Tobelo'),
(32, 'Labuha'),
(32, 'Sanana'),
(32, 'Weda'),

-- Papua Barat (33)
(33, 'Manokwari'),
(33, 'Sorong'),
(33, 'Bintuni'),
(33, 'Ransiki'),
(33, 'Fakfak'),
(33, 'Kaimana'),
(33, 'Babo'),

-- Papua (34)
(34, 'Jayapura'),
(34, 'Abepura'),
(34, 'Sentani'),
(34, 'Biak'),
(34, 'Serui'),
(34, 'Nabire'),
(34, 'Wamena'),
(34, 'Timika'),
(34, 'Merauke'),
(34, 'Sarmi'),
(34, 'Oksibil'),

-- Papua Selatan (35)
(35, 'Merauke'),
(35, 'Boven Digoel'),
(35, 'Mappi'),
(35, 'Asmat'),

-- Papua Tengah (36)
(36, 'Nabire'),
(36, 'Timika'),
(36, 'Paniai'),
(36, 'Dogiyai'),
(36, 'Deiyai'),

-- Papua Pegunungan (37)
(37, 'Wamena'),
(37, 'Jayawijaya'),
(37, 'Pegunungan Bintang'),
(37, 'Yahukimo'),
(37, 'Tolikara'),
(37, 'Lanny Jaya'),

-- Papua Barat Daya (38)
(38, 'Sorong'),
(38, 'Raja Ampat'),
(38, 'Maybrat'),
(38, 'Tambrauw'),
(38, 'Sorong Selatan');
