ALTER TABLE recruiters
ADD COLUMN IF NOT EXISTS is_vip BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vip_start_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS vip_end_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE job_posts
ADD COLUMN IF NOT EXISTS is_vip BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vip_start_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS vip_end_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_recruiters_is_vip ON recruiters(is_vip);
CREATE INDEX IF NOT EXISTS idx_job_posts_is_vip ON job_posts(is_vip);
